#!/bin/zsh
# A shell heredoc to test the example file without manual intervention
# cli input is swallowed in print, however output will be displayed.

# required for loading PATH that contains site packages.
source ~/.zshrc

python example_calculator_repl.py << EOF > test_output
    help
    add 2 3
    mult 2 3
    fac -h
    factorial 5
    factorial five
    factorial 120
    cs "alias works"
    cowsay -h
    cowsay -w hi
    cowsay -w beef
    cowsay
    exit
EOF

diff test_output data/test_output > /dev/null

if (( $? )) then
    echo "Test Failed To Generate Same Expected Output, output file: test_output"
    exit 1
else
    rm test_output
    echo "Test Succeeded"
fi
